### ISSUE TITLE
[Pages] (estrutura da address)

### ISSUE THREAD

**Issue by v0rph** [regedor/GMS-Prototype#11]
Falamos em tentar tirar as pages de **ajtg.com/pages/slug** e passar para a root **ajtg.com/slug**

**Comment by zamith** [comment]
Qual a vantagem disso? Além de não ser REST...

**Comment by regedor** [comment]
Muitas, e continua a ser REST. As paginas podem servir para muitas coisas. convém que tenham links curtos. Quando escolho o slug contactos. Quero a pagina /contactos. e não /pages/contactos. caso contrario o slug não é um slug mas um id.

**Comment by regedor** [comment]
quando isto for feito é preciso rever links nos site em produção! e javascript que esteja relacionado com os links também. Mas podes avançar com isto a qualquer momento. Simplesmente avisa quando estiver num commit para ser ter o cuidado de corrigir links nos conteudos!
