### ISSUE TITLE
Running the master with an error

### ISSUE THREAD

**Issue by zamith** [regedor/GMS-Prototype#4]
I installed the tweet-button gem, and after that did a db_reborn and rake db:fill:nemum_data:all.

Now when I try to access localhost:3000 I get the following error:

URI::InvalidURIError in Posts#index

Showing app/views/posts/_post.html.erb where line #6 raised:

bad URI(is not URI?): Simon Administration.local

Extracted source (around line #6):

3:   <%=raw post.body_html %>
4: </div>
5: <div id="social-buttons">
6:   <%= tweet_button(:via => configatron.site_name, :text => post.title, :count => "none", :url => post_path(post, :only_path => false)) %>
7:   <a name="fb_share" type="button" 
8:     share_url="<%= post_path(post, :only_path => false) %>"> <%= I18n::t("posts.share_on_facebook")%></a>
9:      <script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share"

**Comment by beloso** [comment]
I have the same problem.

**Comment by rmscouto** [comment]
Fixed on last commit. Define a valid site_url on config.yml, for example http://simon.di.uminho.pt.
